import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "@/src/shared/lib/utils";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
  openGraph:{
    title: "Landing Page",
    description: "Generated by create next app",
    url: "https://landing-page-psi.vercel.app/",
    siteName: "Landing Page",
    images:[
      {
        url:"https://landing-page-psi.vercel.app/og-image.png",
        width: 1200,
        height: 630,
        alt: "Landing Page Open Graph Image"
      }
    ],
    locale: "en_US",
    type: "website"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(geistSans.variable, geistMono.variable, "h-full antialiased")}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
